server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.102:1111
    #      config:
    #        server-addr: 192.168.1.102:1111
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由

        - id: payment_routh3 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloudalibaba-sentinel-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/test/**       # 断言，路径相匹配的进行路由

        - id: payment_routh4 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-payment-provider      #匹配后提供服务的路由地址
          predicates:
            - Path=/getway/sentinel/**       # 断言，路径相匹配的进行路由
#eureka:
#  instance:
#    hostname: cloud-gateway-service
#  client: #服务提供者provider注册进eureka服务列表内
#    service-url:
#      register-with-eureka: true
#      fetch-registry: true
#      defaultZone: http://eureka7001.com:7001/eureka
